# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jq-HTmc5S223fso4RvhexI5WLpuOni6S
"""

"""
Model: Random Variable X ~ N(0, 1)

Theory:
E[X] = 0
Var(X) = 1

Goal:
Define theoretical quantities for comparison with simulation
"""

def theoretical_expectation():
    return 0.0


def theoretical_variance():
    return 1.0